### ISSUE TITLE
Facebook public profile is incomplete

### ISSUE THREAD

**Issue by steida** [steida/firebase#1]
https://developers.facebook.com/docs/facebook-login/permissions#reference-public_profile

Firebase 3 should request full public profile as Firebase 2 did.

**Comment by jwngr** [comment]
Known issue and due to the fact that Facebook doesn't return the whole profile even if the individual fields are public. You need to ask for each individual piece of info. This is a top priority to fix and a known regression from the previous API. I expect it to be fixed, but unfortunately it will be on the period of weeks, not days, last I heard :/

**Comment by steida** [comment]
Take your time. I postponed Firebase 3 integration to Este already. Stress will not produce quality software.
