### ISSUE TITLE
Make possible add customized claims the Auth token without server code

### ISSUE THREAD

**Issue by douglascorrea** [steida/firebase#12]
Auth claims help build better security rules.

Today the only way to get it done is using a custom token with server code.

The problem is while using custom tokens we have only 2 choices:
 - Re-implement all auth methods in server side and not use the out-of-box features (Email/Pass, Social)
 - Or using the current out-the-box auth, and exchange the token with the new token generated at server side.

It will be useful to have a way to automatic put claims on auth based on database data or some other rules, maybe integrated with the new triggers solution.

I will understand if this is not in the Firebase roadmap, but I think it is good to bring it here as we have other developers interested in it: https://mail.google.com/mail/u/0/#label/Lists%2Ffirebase-talk/155268cf135aed58

**Comment by jwngr** [comment]
I'm not sure there is a way to securely do what you want and I also am not sure there is a valid use case for it.

Security-wise, tokens are minted via a secret (in the old world) or a service account (in the new world). Secrets and service accounts should never be shared with a client since that poses a huge security risk and therefore this is a bit of a moot topic. But even if we ignore that fact, allowing any client to add custom claims to a token means a malicious attacker could change the auth token to have whatever claims they want, including saying they are some other user or an admin. The whole point of having your own server here is that you need some trusted actor, and an end-user client cannot be that trusted actor.

As for functionality, I'm interested to hear your specific use case. What kind of claims are you looking to add?

P.S. Note that your link is a GMail link and doesn't work.

**Comment by douglascorrea** [comment]
Hi @jwngr ,

Sorry abou the link. The following discussing are about that:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/77i9CRlwg88/5dSIVzXxGwAJ

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/xegiLwPcyow/hO_4lm0eHAAJ

My point here is not let the Client put custom claims on the token, that is absolutely wrong and danger.

What I thought was something like, I create a functionality on the Auth, on Firebase console, where I can set custom claims for specific users manually or set it automatically via Firebase triggers.

The use cases:

1) In the security rules I will be able to simply use auth.isAdmin = true, instead of doing other "joins" with auth.uid and database data.

2) In the client I will be able to make restricted pages just using the User from Auth directly instead of doing another query to check if he is or not admin, in this case.

This also works for the scenario of paid membership. In the case of paid membership, the way to set it should be automatically and not manually. Again, Firebase triggers could fit here.

All the scenarios above are covered by customToken on the server, but, as I said,I imagined something in the Firebase Console where I can set rules for it just to, again, avoid fire up a separated node server for it.

**Comment by jwngr** [comment]
I think all of these use cases are handled just by storing data in your Realtime Database and referencing that data in your Security Rules. I definitely realize the limitations of Firebase Storage Rules not being able to access Realtime Database data, but I'm just not sure I think this kind of functionality opens up that many new options. I also think this is technically much more challenging for us with how the new auth system works. Triggers could possibly fit in here, but I'm not sure at this point what it would look like.

**Comment by douglascorrea** [comment]
@jwngr you are right, as far we can have a good workaround that currently works (storing the data in database and referencing in the security rules) and also being able to create custom tokens in special case.
And as I also understand that will be much more challenging to create does not make sense list it as requirement.
We can close this issue.
