### ISSUE TITLE
Put back simple one line api endpoint

### ISSUE THREAD

**Issue by steida** [steida/firebase#6]
@jwngr Having two big configs is not nice for DX. Any chance to fix it somehow in future?

**Comment by jwngr** [comment]
What exactly are you referring to? Are you referring to the old `new Firebase(url)` versus the new `firebase.initializeApp(config)`? I assume by two configs you mean (1) the service account JSON file and (2) the config you pass to `initializeApp()` which includes the service account.

We are talking about what to do with the service account restriction and how to solve the isomorphic app case in a sensible manner. There is a strong contingent that thinks that having all the auth methods in the Node.js SDK leads devs to do insecure and / or plain incorrect things and they would be better off with an admin API for those things. For example, an admin API for user management has long been needed and would solve many of the complaints people have with the new SDK.

I still am trying to find a good argument for including auth methods like anonymous auth and email / password auth in the server SDKs. There are certainly reasons for acting on behalf of a user, but I'm not sure why an isomorphic API is better than some other admin API. Maybe you can explain your use cases and impart some knowledge on me since I don't have a ton of experience making isomorphic apps. How does auth fit into them?

**Comment by steida** [comment]
With Firebase, I rarely (never) need server side auth. That's because we don't need server-side rendering for a user protected data. Google bot can't log in to app and read them anyway.

So we don't need super admin rules on the server side. For me, the initializeApp can be perfectly the same everywhere. It also allows me to provide ready to use app boilerplate without all auth ceremony in Node.

**Comment by jwngr** [comment]
So would a completely unauthenticated Node.js SDK solve your existing issues with isomorphic apps?

**Comment by steida** [comment]
Sure, I never used server side authentication. Sure it has its own benefits but I haven't a real use case yet.

**Comment by steida** [comment]
Btw, by isomorphic lib (client + server) I mean isomorphic API. Ofc there are implementation details, but API should be the same.

**Comment by rkoberg** [comment]
Well, we should be able to use cookie/token authentication on the server to make a request to firebase. In an isomorphic app, where a user's initial request is to a protected page, it should render that way on the server. It should not use the react router to redirect on the server, and send, say, a login page. And then when sent to the client, the browser renders the login page (quick flash) and react router reroutes to the protected page. (This was an annoying/unsightly thing on the firebase console.)

**Comment by steida** [comment]
@rkoberg: Sure, in the ideal world. But Firebase team has to do a lot off trade-offs and priorities. That's what my comment was about.

**Comment by steida** [comment]
@jwngr 

> So would a completely unauthenticated Node.js SDK solve your existing issues with isomorphic apps?

Any progress, please? All we need for server render is ability to read public data without authentication at all. And without forcing Este users to set up all that Node ceremony.

**Comment by jwngr** [comment]
Un-authenticated access to the Node.js SDK is coming very soon. Should be this week assuming no blocking issues come up with the release. Full authentication methods in the Node.js SDK like email / password, anonymous auth, etc. will still take some time, but we are actively working on it.

Sounds like this week's release should unblock you though 💃

**Comment by jwngr** [comment]
The `3.1.0` release of the JavaScript SDK just went out. Unauthenticated access is now available. Release notes are [here](https://firebase.google.com/support/release-notes/js#3.1.0).

**Comment by steida** [comment]
Awesome. Thank you.

**Comment by steida** [comment]
@jwngr Docs about unauthenticated access should be updated, but it's probably already on your internal issue tracker.

**Comment by jwngr** [comment]
Good call. I actually forgot to update these. I'll get them updated soon.
